//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string UI_TOUCH = "ui-touch";
        
        public const string GRAB_INTERACTABLE = "grab-interactable";
        
        public const string RELEASE_INTERACTABLE = "release-interactable";
        
        public const string GLOVE_TEST = "glove-test";
    }
}
