//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string PICK_INTERACTABLE_LEFT = "pick-interactable-left";
        
        public const string GAME_START = "game_start";
        
        public const string PICK_INTERACTABLE_RIGHT = "pick-interactable-right";
    }
}
